// <auto-generated />
namespace movieLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IdentityModelFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdentityModelFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201907311703106_IdentityModelFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
